Update setup.py to allow install
I am no python packaging expert so this may be entirely wrong. However,
currently:

```
$docker run --rm -v $PWD:$PWD -w $PWD -it --entrypoint bash python -c 'pip install . -r requirements.txt; i3-agenda'
ModuleNotFoundError: No module named 'i3_agenda.i3_agenda'; 'i3_agenda' is not a package
```

This PR fixes this and allows installing